[2024-11-11T07:15:44.882+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-11T07:15:44.914+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: python_op_sample_1.create_save_df manual__2024-11-11T07:15:35.274299+00:00 [queued]>
[2024-11-11T07:15:44.930+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: python_op_sample_1.create_save_df manual__2024-11-11T07:15:35.274299+00:00 [queued]>
[2024-11-11T07:15:44.930+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-11T07:15:44.952+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): create_save_df> on 2024-11-11 07:15:35.274299+00:00
[2024-11-11T07:15:44.965+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=55025) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-11T07:15:44.967+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'python_op_sample_1', 'create_save_df', 'manual__2024-11-11T07:15:35.274299+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dag1_py_op_sample.py', '--cfg-path', '/tmp/tmpm87iatol']
[2024-11-11T07:15:44.967+0000] {standard_task_runner.py:72} INFO - Started process 55027 to run task
[2024-11-11T07:15:44.968+0000] {standard_task_runner.py:105} INFO - Job 20: Subtask create_save_df
[2024-11-11T07:15:45.045+0000] {task_command.py:467} INFO - Running <TaskInstance: python_op_sample_1.create_save_df manual__2024-11-11T07:15:35.274299+00:00 [running]> on host b86342c5c47f
[2024-11-11T07:15:45.205+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='python_op_sample_1' AIRFLOW_CTX_TASK_ID='create_save_df' AIRFLOW_CTX_EXECUTION_DATE='2024-11-11T07:15:35.274299+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-11T07:15:35.274299+00:00'
[2024-11-11T07:15:45.206+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-11T07:15:45.207+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-11T07:15:45.207+0000] {logging_mixin.py:190} INFO - Current task name:create_save_df state:running start_date:2024-11-11 07:15:44.915166+00:00
[2024-11-11T07:15:45.208+0000] {logging_mixin.py:190} INFO - Dag name:python_op_sample_1 and current dag run status:running
[2024-11-11T07:15:45.208+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-11T07:15:45.210+0000] {logging_mixin.py:190} INFO - Starting with the first task in my Python Op Dag
[2024-11-11T07:15:45.250+0000] {logging_mixin.py:190} INFO - My first task in the Dag is finished
[2024-11-11T07:15:45.251+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-11T07:15:45.268+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-11T07:15:45.269+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=python_op_sample_1, task_id=create_save_df, run_id=manual__2024-11-11T07:15:35.274299+00:00, execution_date=20241111T071535, start_date=20241111T071544, end_date=20241111T071545
[2024-11-11T07:15:45.289+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-11T07:15:45.290+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-11T07:15:45.291+0000] {logging_mixin.py:190} INFO - Dag name:python_op_sample_1 queued_at:2024-11-11 07:15:35.354362+00:00
[2024-11-11T07:15:45.292+0000] {logging_mixin.py:190} INFO - Task hostname:b86342c5c47f operator:PythonOperator
[2024-11-11T07:15:45.348+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-11T07:15:45.398+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-11T07:15:45.407+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
